```{r}
# if (!require("pacman")) install.packages("pacman") # just once
pacman::p_load(tidyverse, janitor, skimr)
```

Import data from .csv, and visualize its structure and variables

```{r}
raw <- readr::read_csv("data/peanut_smut_survey.csv")
raw %>% glimpse
skimr::skim(raw)
```

Calculate incidences (general, and for each severity class) and disease severity index (DSI)

```{r}
dat <- 
  raw %>% 
  mutate(id=interaction(department, harvest_year)) %>% 
  mutate(diseased_pods = rowSums(select(., matches('class_')))) %>% 
  mutate(global_inc=diseased_pods/total_pods, 
         class.1_inc=class_1/total_pods,
         class.2_inc=class_2/total_pods,
         class.3_inc=class_3/total_pods,
         class.4_inc=class_4/total_pods 
         ) %>% 
  rowwise() %>% 
  mutate(DSI = ((1*class_1+2*class_2+3*class_3+4*class_4)/(total_pods*4))*100)%>% 
    mutate_at(vars(matches('inc|sev')), ~(. * 100 )%>% round(2))

# dat %>% 
#   select(id, total_pods, starts_with("class")) %>% 
#   rowwise() %>% 
#   mutate(DSI = ((1*class_1+2*class_2+3*class_3+4*class_4)/(total_pods*4))*100) %>% 
#   ggplot()+
#   aes(DSI)+
#   geom_histogram()

dat %>% view
```

Check the full dataset via a two-way table (year and location)

Each count within the above two-way table represents the number of field assessed

```{r}
dat %>% 
  tabyl(department, harvest_year) %>% 
  adorn_totals()
```

Save the tidy data for further analysis

```{r}
save(dat, file="data/data.RData")
```

