```{r, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
pacman::p_load(tidyverse, janitor)
load("data/data.RData")
knitr::knit_child('data_and_settings.Rmd', quiet = TRUE)
```

Filter the dataset for those environments (year * department) with at least 10% of disease global incidence range

```{r}
dat1 <- dat %>% 
  group_by(harvest_year, department)  %>% 
  mutate(min = min(global_inc),
         max = max(global_inc),
         range = max-min,
         keep = case_when(range >.099 ~ "yes", 
                          TRUE ~ "no")) %>% 
  ungroup %>% 
  filter(keep=="yes") %>% 
  as.data.frame() # for avoiding bug with ggpredict package
```

Check new variables 

```{r}
dat1 %>% 
  tabyl(department, harvest_year) %>% 
  adorn_totals()

dat1 %>% head(15)
```


# Modeling

```{r}
pacman::p_load(car, 
               nlme,        # for adjusting the mixed linear regression 
               lattice, 
               performance, # for calculating model R2
               ggeffects,   # for estimating predicted values
               ggtext,      # for including model coefficients and R2 in the plots
               glue         # for writing model coefficients and R2
               )
ctrl <- lmeControl(opt='optim')
```

Class 1 incidence vs global incidence

```{r}
m1<-lme(class.1_inc ~ global_inc, 
          random = ~global_inc|id,
          weights=varPower(form = ~global_inc),
          data=dat1)
```


```{r}
# png(filename="plots/class1_reg_diagnostics.png", 
#     type="cairo",
#     units="in", 
#     width=4, 
#     height=4, 
#     pointsize=12, 
#     res=96)
plot(m1)
# dev.off()
```

```{r}
summary(m1)
```

Id-level plots

```{r}
# png(filename="plots/class1_id_level.png", 
#     type="cairo",
#     units="in", 
#     width=6, 
#     height=4, 
#     pointsize=12, 
#     res=96)

xyplot(class.1_inc~global_inc | id, data=dat1, fit=m1,
       strip=strip.custom(bg="white"), 
       par.strip.text=list(cex=.5),
       pch=16, cex=0.7, col='grey30',
       panel = function(x, y, ..., fit, subscripts) {
         panel.xyplot(x, y, ...)
         ypred <- fitted(fit)[subscripts]
         panel.lines(x, ypred, col="black", lwd=1)
       },
       ylab="Class-1 Incidence ", xlab="Global incidence ")
# dev.off()
```

Fixed effects plot 

```{r}
df1 <- data.frame(x = 0, y = .5,
  label = glue(
    "y = {round(summary(m1)$tTable[1,1],4)} + {round(summary(m1)$tTable[2,1],3)} * x\n
    (*R<sup>2</sup>* = {round(r2_nakagawa(m1)$R2_conditional, 2)})")  
  ) 

p1 <- ggpredict(m1, terms="global_inc [all]") %>% 
  ggplot()+
  aes(x = x, y = predicted) +
  geom_smooth(data=dat1, aes(x = global_inc, y = class.1_inc, group=id), 
              method="lm", se=F, col="grey30", size=.5)+
  geom_point(data=dat1, aes(x = global_inc, y = class.1_inc), size=.3)+
  geom_line(size=1, col="#3366FF")+
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1) +
  labs(y="Class-1 Incidence ", x="Global incidence")+
  my_theme + conc_set +
  geom_richtext(
    data = df1,
    aes(x=x, y=y, label = label),
    hjust = 0, vjust = 1, 
    label.color = NA,
    fill = alpha("grey30", .2)
  )
p1
```

Continue with all the class levels...

```{r}
m2<-lme(class.2_inc~global_inc, 
          random = ~global_inc|id,
          weights=varPower(form = ~global_inc),
          data=dat1)
```

```{r}
# png(filename="plots/class2_reg_diagnostics.png", 
#     type="cairo",
#     units="in", 
#     width=4, 
#     height=4, 
#     pointsize=12, 
#     res=96)
plot(m2)
# dev.off()
```


```{r}
summary(m2)
```

```{r}
# png(filename="plots/class2_id_level.png", 
#     type="cairo",
#     units="in", 
#     width=6, 
#     height=4, 
#     pointsize=12, 
#     res=96)
xyplot(class.2_inc~global_inc | id, data=dat1, fit=m2,
       strip=strip.custom(bg="white"), 
       par.strip.text=list(cex=.5),
       pch=16, cex=0.7, col='grey30',
       panel = function(x, y, ..., fit, subscripts) {
         panel.xyplot(x, y, ...)
         ypred <- fitted(fit)[subscripts]
         panel.lines(x, ypred, col="black", lwd=1)
       },
       ylab="Class-2 Incidence", xlab="Global incidence")
# dev.off()
```


```{r}
df2 <- data.frame(x = 0, y = .5,
  label = glue(
    "y = {round(summary(m2)$tTable[1,1],4)} + {round(summary(m2)$tTable[2,1],3)} * x\n
    (*R<sup>2</sup>* = {round(r2_nakagawa(m2)$R2_conditional, 2)})")  
  ) 

p2 <- ggpredict(m2, terms="global_inc [all]") %>% 
  ggplot() +
  aes(x = x, y = predicted)+
  geom_smooth(data=dat1, aes(x = global_inc, y = class.2_inc, group=id), 
              method="lm", se=F, col="grey30", size=.5, alpha=.5)+
  geom_point(data=dat1, aes(x = global_inc, y = class.2_inc), size=.3)+
  geom_line(size=1, col="#3366FF")+
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1) +
  labs(y="Class-2 Incidence", x="Global incidence")+
  my_theme+conc_set + 
    geom_richtext(
    data = df2,
    aes(x=x, y=y, label = label),
    hjust = 0, vjust = 1, 
    label.color = NA,
    fill = alpha("grey30", .2)
  )
p2
```


```{r}
m3<-lme(class.3_inc~global_inc, 
        random = ~global_inc|id,
        control=ctrl,
        weights=varPower(form = ~global_inc),
        data=dat1)
```


```{r}
# png(filename="plots/class3_reg_diagnostics.png", 
#     type="cairo",
#     units="in", 
#     width=4, 
#     height=4, 
#     pointsize=12, 
#     res=96)
plot(m3)
# dev.off()
```


```{r}
# png(filename="plots/class3_id_level.png", 
#     type="cairo",
#     units="in", 
#     width=6, 
#     height=4, 
#     pointsize=12, 
#     res=96)
xyplot(class.3_inc~global_inc | id, data=dat1, fit=m3,
       strip=strip.custom(bg="white"), 
       par.strip.text=list(cex=.5),
       pch=16, cex=0.7, col='grey30',
       panel = function(x, y, ..., fit, subscripts) {
         panel.xyplot(x, y, ...)
         ypred <- fitted(fit)[subscripts]
         panel.lines(x, ypred, col="black", lwd=1)
       },
       ylab="Class-3 Incidence", xlab="Global incidence ")
# dev.off()
```


```{r}
df3 <- data.frame(x = 0, y = .5,
  label = glue(
    "y = {round(summary(m3)$tTable[1,1],3)} + {round(summary(m3)$tTable[2,1],3)} * x\n
    (*R<sup>2</sup>* = {round(r2_nakagawa(m3)$R2_conditional, 2)})")  
  ) 

p3 <- ggpredict(m3, terms="global_inc [all]") %>% 
  ggplot() +
  aes(x = x, y = predicted)+
  geom_smooth(data=dat1, aes(x = global_inc, y = class.3_inc, group=id), 
              method="lm", se=F, col="grey30", size=.5)+
  geom_point(data=dat1, aes(x = global_inc, y = class.3_inc), size=.3)+
  geom_line(size=1, col="#3366FF")+
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1) +
  labs(y="Class-3 Incidence ", x="Global incidence ")+
  my_theme+conc_set + 
  geom_richtext(
    data = df3,
    aes(x=x, y=y, label = label),
    hjust = 0, vjust = 1, 
    label.color = NA,
    fill = alpha("grey30", .2)
  )
p3
```

```{r}
m4<-lme(class.4_inc~global_inc, 
          random = ~global_inc|id,
          control=ctrl,
          weights=varPower(form = ~global_inc),
          data=dat1)
```


```{r}
# png(filename="plots/class4_reg_diagnostics.png", 
#     type="cairo",
#     units="in", 
#     width=4, 
#     height=4, 
#     pointsize=12, 
#     res=96)
plot(m4)
# dev.off()
```

```{r}
# png(filename="plots/class4_id_level.png", 
#     type="cairo",
#     units="in", 
#     width=6, 
#     height=4, 
#     pointsize=12, 
#     res=96)
xyplot(class.4_inc~global_inc|id, data=dat1, fit=m4,
       strip=strip.custom(bg="white"), 
       par.strip.text=list(cex=.5),
       pch=16, cex=0.7, col='grey30',
       panel = function(x, y, ..., fit, subscripts) {
         panel.xyplot(x, y, ...)
         ypred <- fitted(fit)[subscripts]
         panel.lines(x, ypred, col="black", lwd=1)
       },
       ylab="Class-4 Incidence ", xlab="Global incidence ")
# dev.off()
```

```{r}
df4 <- data.frame(x = 0, y = .5,
  label = glue(
    "y = {round(summary(m4)$tTable[1,1],3)} + {round(summary(m4)$tTable[2,1],3)} * x\n
    (*R<sup>2</sup>* = {round(r2_nakagawa(m4)$R2_conditional, 2)})")  
  ) 

p4 <- ggpredict(m4, terms="global_inc [all]") %>% 
ggplot() +
  aes(x = x, y = predicted)+
  geom_smooth(data=dat1, aes(x = global_inc, y = class.4_inc, group=id), 
              method="lm", se=F, col="grey30", size=.5)+
  geom_point(data=dat1, aes(x = global_inc, y = class.4_inc), size=.3)+
  geom_line(size=1, col="#3366FF")+    
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1) +
  labs(y="Class-4 Incidence ", x="Global incidence ")+
  my_theme + 
  conc_set + 
    geom_richtext(
    data = df4,
    aes(x=x, y=y, label = label),
    hjust = 0, vjust = 1, 
    label.color = NA,
    fill = alpha("grey30", .2)
  ) 
p4
```


```{r}
dat1<- dat1 %>% 
  mutate(class.3.4_inc=(class_3+class_4)/total_pods)

m3.4<-lme(class.3.4_inc~global_inc, 
          random = ~global_inc|id,
          control=ctrl,
          weights=varPower(form = ~global_inc),
          data=dat1)
```


```{r}
# png(filename="plots/class3.4_reg_diagnostics.png", 
#     type="cairo",
#     units="in", 
#     width=4, 
#     height=4, 
#     pointsize=12, 
#     res=96)
plot(m3.4)
# dev.off()
```

```{r}
# png(filename="plots/class3.4_id_level.png", 
#     type="cairo",
#     units="in", 
#     width=6, 
#     height=4, 
#     pointsize=12, 
#     res=96)
xyplot(class.3.4_inc~global_inc | id, data=dat1, fit=m3.4,
       strip=strip.custom(bg="white"), 
       par.strip.text=list(cex=.5),
       pch=16, cex=0.7, col='grey30',
       panel = function(x, y, ..., fit, subscripts) {
         panel.xyplot(x, y, ...)
         ypred <- fitted(fit)[subscripts]
         panel.lines(x, ypred, col="black", lwd=1)
       },
       ylab="Class-4 Incidence ", xlab="Global incidence ")
# dev.off()
```

```{r}
df3.4 <- data.frame(x = 0, y = .5,
  label = glue(
    "y = {round(summary(m3.4)$tTable[1,1],3)} + {round(summary(m3.4)$tTable[2,1],3)} * x\n
    (*R<sup>2</sup>* = {round(r2_nakagawa(m3.4)$R2_conditional, 2)})")  
  ) 

p3.4 <- ggpredict(m3.4, terms="global_inc [all]") %>% 
  ggplot() +
  aes(x = x, y = predicted)  +
  geom_smooth(data=dat1, aes(x = global_inc, y = class.3.4_inc, group=id), 
              method="lm", se=F, col="grey30", size=.5)+
  geom_point(data=dat1, aes(x = global_inc, y = class.3.4_inc), size=.3)+
  geom_line(size=1, col="#3366FF")+
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1) +
  labs(y="Class-3+4 Incidence ", x="Global incidence ")+
  my_theme + 
  conc_set + 
  geom_richtext(
    data = df3.4,
    aes(x=x, y=y, label = label),
    hjust = 0, vjust = 1, 
    label.color = NA,
    fill = alpha("grey30", .2)
  ) 
p3.4
```

```{r}
pacman::p_load(patchwork)
((p1 + p2) / (p3 + p4)) | p3.4
```

```{r, eval =F}
ggsave(last_plot(), file = "plots/regressions.png", width = 9, height = 6)
```
